#!/usr/bin/env python3
"""Compute corrected ground-truth energy totals for the Riverbend sandbox.

Applies the documented corrections from instructor-answer-key-v1.md:
  Flaw 1: HWB-01 electricity is MWh in a kWh column -> x1000
  Flaw 3: RBC-01 October rows duplicated -> dedup
  Flaw 6: RPS-01 July electricity has an extra digit -> /10
  Flaw 9: CSV RBC-01 March electricity (246,800) loses to the utility bill (268,400)

Writes course-build/reference-totals-2025.md (instructor-only).
Run after any data regeneration: python3 reference-totals.py
"""
import csv, os
from collections import defaultdict
from openpyxl import load_workbook

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "..", "sandbox-client", "data")
OUT = os.path.join(HERE, "..", "reference-totals-2025.md")

elec = defaultdict(float)   # facility -> kWh
gas = defaultdict(float)    # facility -> therms

# --- corporate energy CSV, with corrections ---
seen = set()
with open(os.path.join(DATA, "energy-consumption-2025.csv")) as f:
    for row in csv.DictReader(f):
        key = (row["facility_id"], row["month"], row["energy_type"])
        if key in seen:                     # flaw 3: duplicated October resubmission
            continue
        seen.add(key)
        v = float(row["consumption"])
        if key == ("RPS-01", "2025-07", "Electricity"):
            v = v / 10                      # flaw 6: extra digit
        if key == ("RBC-01", "2025-03", "Electricity"):
            v = 268400                      # flaw 9: bill is authoritative
        (elec if row["energy_type"] == "Electricity" else gas)[row["facility_id"]] += v

# --- Headwater xlsx, with unit correction ---
ws = load_workbook(os.path.join(DATA, "headwater-brands-energy-2025.xlsx")).active
for r in ws.iter_rows(min_row=6, values_only=True):
    if not r or not r[0]:
        continue
    site, period, commodity, qty, uom = r
    qty = float(qty)
    if commodity == "ELEC":
        if site == "HWB-01":
            qty *= 1000                     # flaw 1: MWh recorded in kWh column
        elec[site] += qty
    else:
        gas[site] += qty

DIV = {"RBC": "Riverbend Bottling Co.", "HWB": "Headwater Brands",
       "RPS": "Riverbend Packaging Solutions", "CDL": "Coldstream Distribution & Logistics",
       "COR": "Corporate"}

div_e, div_g = defaultdict(float), defaultdict(float)
for k, v in elec.items(): div_e[DIV[k[:3]]] += v
for k, v in gas.items():  div_g[DIV[k[:3]]] += v

GAS_FACTOR = 0.00531  # mt CO2e per therm (EPA, natural gas) — same factor Kith taught

with open(OUT, "w") as f:
    f.write("# Riverbend Reference Totals — CY2025 (corrected ground truth)\n\n")
    f.write("**INSTRUCTOR ONLY.** Generated by `tools/reference-totals.py` after applying\n")
    f.write("the answer-key corrections (flaws 1, 3, 6, 9). Use for grading Week 3 inventories.\n")
    f.write("Student answers within ~1% of these (or with documented alternative treatment of\n")
    f.write("RBC-06/leased offices/estimated gap months) are correct.\n\n")
    f.write("## By facility\n\n| Facility | Electricity (kWh) | Natural gas (therms) | Gas Scope 1 (mt CO2e) |\n|---|---:|---:|---:|\n")
    for fid in sorted(set(elec) | set(gas)):
        f.write(f"| {fid} | {elec[fid]:,.0f} | {gas[fid]:,.0f} | {gas[fid]*GAS_FACTOR:,.0f} |\n")
    f.write("\n## By division\n\n| Division | Electricity (kWh) | Natural gas (therms) | Gas Scope 1 (mt CO2e) |\n|---|---:|---:|---:|\n")
    for d in DIV.values():
        f.write(f"| {d} | {div_e[d]:,.0f} | {div_g[d]:,.0f} | {div_g[d]*GAS_FACTOR:,.0f} |\n")
    te, tg = sum(elec.values()), sum(gas.values())
    f.write(f"| **TOTAL** | **{te:,.0f}** | **{tg:,.0f}** | **{tg*GAS_FACTOR:,.0f}** |\n\n")
    f.write("## Notes for graders\n\n")
    f.write("- Electricity (Scope 2) emissions depend on the eGRID factor vintage/state the\n")
    f.write("  student chose — grade the *method and documentation*, not a single number.\n")
    f.write(f"- Gas Scope 1 uses {GAS_FACTOR} mt CO2e/therm (EPA), the factor taught in the course.\n")
    f.write("- RBC-06 (divested Aug 2025): totals above INCLUDE its Jan-Aug consumption.\n")
    f.write("  Excluding it entirely is acceptable if documented as a boundary decision.\n")
    f.write("- RBC-04 gap months (Mar-May) are NOT estimated in these totals; a student who\n")
    f.write("  interpolates will land ~2-3% higher on RBC-04 — fine if tagged as estimated.\n")
    f.write("- Fleet fuel, refrigerants, and leased offices are excluded here (fleet is a\n")
    f.write("  separate Scope 1 line; refrigerants are unquantifiable by design).\n")

print("Wrote", os.path.normpath(OUT))
